# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MongoGIS
tagline:          'Giving MongoDB the Way to Play with the GIS Community'
description:      'GIS tools built for MongoDB.'
url:              http://www.mongogis.org

author:
  name:           'geosky'
  url:            https://twitter.com/geosky

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/mongogis/mongodb-gdal-driver
